services:
  - type: web
    name: django-study-base
    runtime: python
    buildCommand: ./_scripts/build_render.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.product
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHON_VERSION
        value: 3.12.3
    disk:
      name: django-sqlite-data
      mountPath: /data
      sizeGB: 1
